// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://khjlqrsooawogpvotpal.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtoamxxcnNvb2F3b2dwdm90cGFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMzI2NzUsImV4cCI6MjA2NDcwODY3NX0.8zoTv3l4JPG077QHDZPHKe3wjh-d2WAZ2hTq64x1apE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);